root: ./

redirects:  
- 'masternode/masternode-setup-guide/': './masternode-and-dex/masternode/masternode-setup-guide.md'
- 'get-started/how_to_read/': './README.md'
- 'get-started/productoverview/': './general/introduction.md'

