root: ./

redirects:  
    get-started/productoverview/: ./general/introduction.md
    masternode/masternode-setup-guide/: ./masternode-and-dex/masternode/masternode-setup-guide.md
    get-started/how_to_read/: ./README.md
    get-started/wallet/: ./general/how-to-connect-to-tomochain-network/tomowallet.md
    get-started/voting/: ./general/staking.md
