redirects:  
    masternode/masternode-setup-guide/: ./masternode-and-dex/masternode/masternode-setup-guide.md
    get-started/how_to_read/: ./README.md
    get-started/productoverview/: ./general/introduction.md
    get-started/wallet/: ./general/how-to-connect-to-tomochain-network/tomowallet.md
    get-started/voting/: ./general/staking.md
    general/networks/: ./developer-guide/working-with-tomochain.md
    general/faq/: ./faq/README.md
    masternode/requirements/: ./masternode-and-dex/masternode/requirements.md
    masternode/masternode-setup-guide/: ./masternode-and-dex/masternode/masternode-setup-guide.md
    masternode/tomonative/: ./masternode-and-dex/masternode/run-a-full-node/binary.md
    masternode/create-tomochain-masternode/: ./masternode-and-dex/masternode/run-a-full-node/create-a-tomochain-masternode.md
    masternode/tmn/: ./masternode-and-dex/masternode/run-a-full-node/tmn.md
